import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/ui/navbar";
import { FavouritesProvider } from "@/context/favouritesContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quote Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}>
        
        <div className="flex-1 bg-purple-100  text-black flex justify-center items-center">
          <div className="rounded-lg p-3 border-2 border-purple-700 w-full max-w-5xl">
           <div className=" bg-white rounded-lg p-1 w-full max-w-5xl h-[600px] border border-purple-700">
            <Navbar />
          {/* wraped in  provider context to share favourites , now any componet can access favourites, add, remove inside app/ */}
          <FavouritesProvider>{children}</FavouritesProvider> 
          </div> 
          </div> 
        </div>
        
      </body>
    </html>
  );
}
